import type {
  ApprovalItem,
  BookingStatus,
  Member,
  Role,
  Room,
  RoomBooking,
  Song,
  SongRequest,
  WorshipScale,
} from "@/lib/types"

export const members: Member[] = [
  {
    id: "mem-001",
    name: "Mariana Azevedo",
    email: "mariana@siloé.org.br",
    phone: "(61) 99812-4411",
    role: "admin",
    status: "ativo",
    category: "lider",
    birthDate: "1988-08-14",
    baptismDate: "2010-04-18",
    maritalStatus: "casado",
    ministries: ["Secretaria", "Recepção"],
    growthSteps: [
      { id: "g1", title: "Batismo nas Águas", completed: true, completedAt: "2010-04-18" },
      { id: "g2", title: "Curso de Integração", completed: true, completedAt: "2010-06-01" },
      { id: "g3", title: "Discipulado 1:1", completed: true, completedAt: "2011-02-15" },
      { id: "g4", title: "Escola de Líderes", completed: true, completedAt: "2012-11-20" },
    ],
  },
  {
    id: "mem-002",
    name: "Rafael Monteiro",
    email: "rafael@siloé.org.br",
    phone: "(61) 98144-5522",
    role: "lider_louvor",
    status: "ativo",
    category: "lider",
    birthDate: "1992-03-25",
    baptismDate: "2014-11-09",
    maritalStatus: "casado",
    ministries: ["Louvor", "Mídia"],
    growthSteps: [
      { id: "g1", title: "Batismo nas Águas", completed: true, completedAt: "2014-11-09" },
      { id: "g2", title: "Curso de Integração", completed: true, completedAt: "2015-01-10" },
      { id: "g3", title: "Discipulado 1:1", completed: true, completedAt: "2015-08-30" },
      { id: "g4", title: "Escola de Líderes", completed: true, completedAt: "2016-12-05" },
    ],
  },
  {
    id: "mem-003",
    name: "Priscila Nogueira",
    email: "priscila@siloé.org.br",
    phone: "(61) 99311-8833",
    role: "lider_salas",
    status: "ativo",
    category: "lider",
    birthDate: "1990-11-02",
    baptismDate: "2012-09-16",
    maritalStatus: "casado",
    ministries: ["Salas", "Kids"],
    growthSteps: [
      { id: "g1", title: "Batismo nas Águas", completed: true, completedAt: "2012-09-16" },
      { id: "g2", title: "Curso de Integração", completed: true, completedAt: "2012-11-01" },
      { id: "g3", title: "Discipulado 1:1", completed: true, completedAt: "2013-05-12" },
      { id: "g4", title: "Escola de Líderes", completed: true, completedAt: "2014-10-18" },
    ],
  },
  {
    id: "mem-004",
    name: "André Luiz",
    email: "andre@siloé.org.br",
    phone: "(61) 98765-4321",
    role: "membro",
    status: "ativo",
    category: "membro",
    birthDate: "1995-08-28",
    baptismDate: "2018-05-20",
    maritalStatus: "solteiro",
    ministries: ["Intercessão"],
    growthSteps: [
      { id: "g1", title: "Batismo nas Águas", completed: true, completedAt: "2018-05-20" },
      { id: "g2", title: "Curso de Integração", completed: true, completedAt: "2018-08-10" },
      { id: "g3", title: "Discipulado 1:1", completed: true, completedAt: "2019-03-15" },
      { id: "g4", title: "Escola de Líderes", completed: false },
    ],
  },
  {
    id: "mem-005",
    name: "Camila Rocha",
    email: "camila@siloé.org.br",
    phone: "(61) 99123-9988",
    role: "membro",
    status: "ativo",
    category: "membro",
    birthDate: "1997-04-12",
    baptismDate: "2020-02-16",
    maritalStatus: "solteiro",
    ministries: ["Louvor"],
    growthSteps: [
      { id: "g1", title: "Batismo nas Águas", completed: true, completedAt: "2020-02-16" },
      { id: "g2", title: "Curso de Integração", completed: true, completedAt: "2020-05-01" },
      { id: "g3", title: "Discipulado 1:1", completed: false },
      { id: "g4", title: "Escola de Líderes", completed: false },
    ],
  },
  {
    id: "mem-006",
    name: "Tiago Martins",
    email: "tiago@siloé.org.br",
    phone: "(61) 98444-1122",
    role: "membro",
    status: "ativo",
    category: "congregado",
    birthDate: "2001-12-05",
    maritalStatus: "solteiro",
    ministries: ["Jovens"],
    growthSteps: [
      { id: "g1", title: "Batismo nas Águas", completed: false },
      { id: "g2", title: "Curso de Integração", completed: true, completedAt: "2026-02-10" },
      { id: "g3", title: "Discipulado 1:1", completed: false },
      { id: "g4", title: "Escola de Líderes", completed: false },
    ],
  },
  {
    id: "mem-007",
    name: "Beatriz Lima",
    email: "beatriz@siloé.org.br",
    phone: "(61) 99555-7788",
    role: "membro",
    status: "ativo",
    category: "membro",
    birthDate: "1993-01-30",
    baptismDate: "2016-07-24",
    maritalStatus: "casado",
    ministries: ["Kids"],
    growthSteps: [
      { id: "g1", title: "Batismo nas Águas", completed: true, completedAt: "2016-07-24" },
      { id: "g2", title: "Curso de Integração", completed: true, completedAt: "2016-09-15" },
      { id: "g3", title: "Discipulado 1:1", completed: true, completedAt: "2017-04-10" },
      { id: "g4", title: "Escola de Líderes", completed: true, completedAt: "2018-11-20" },
    ],
  },
  {
    id: "mem-008",
    name: "Lucas Fernandes",
    email: "lucas@siloé.org.br",
    phone: "(61) 99222-3344",
    role: "membro",
    status: "ativo",
    category: "diacono",
    birthDate: "1986-09-18",
    baptismDate: "2008-11-02",
    maritalStatus: "casado",
    ministries: ["Diaconia"],
    growthSteps: [
      { id: "g1", title: "Batismo nas Águas", completed: true, completedAt: "2008-11-02" },
      { id: "g2", title: "Curso de Integração", completed: true, completedAt: "2009-01-15" },
      { id: "g3", title: "Discipulado 1:1", completed: true, completedAt: "2009-08-20" },
      { id: "g4", title: "Escola de Líderes", completed: true, completedAt: "2011-06-10" },
    ],
  },
  {
    id: "mem-009",
    name: "Marcos Oliveira",
    email: "marcos@siloé.org.br",
    phone: "(61) 98777-6655",
    role: "tesoureiro",
    status: "ativo",
    category: "lider",
    birthDate: "1982-06-10",
    baptismDate: "2005-03-12",
    maritalStatus: "casado",
    ministries: ["Tesouraria", "Finanças"],
    growthSteps: [
      { id: "g1", title: "Batismo nas Águas", completed: true, completedAt: "2005-03-12" },
      { id: "g2", title: "Curso de Integração", completed: true, completedAt: "2005-05-01" },
      { id: "g3", title: "Discipulado 1:1", completed: true, completedAt: "2006-01-15" },
      { id: "g4", title: "Escola de Líderes", completed: true, completedAt: "2007-09-30" },
    ],
  },
  {
    id: "mem-010",
    name: "Fernanda Souza",
    email: "fernanda@siloé.org.br",
    phone: "(61) 99666-4433",
    role: "secretaria",
    status: "ativo",
    category: "lider",
    birthDate: "1991-08-20",
    baptismDate: "2013-10-06",
    maritalStatus: "casado",
    ministries: ["Secretaria", "Eventos"],
    growthSteps: [
      { id: "g1", title: "Batismo nas Águas", completed: true, completedAt: "2013-10-06" },
      { id: "g2", title: "Curso de Integração", completed: true, completedAt: "2013-12-01" },
      { id: "g3", title: "Discipulado 1:1", completed: true, completedAt: "2014-06-20" },
      { id: "g4", title: "Escola de Líderes", completed: true, completedAt: "2015-11-15" },
    ],
  },
]

export const financialTransactions = [
  {
    id: "tx-001",
    type: "receita" as const,
    category: "Dízimos" as const,
    description: "Dízimo de Membro - Transferência",
    amount: 1450.00,
    date: "2026-08-24",
    account: "Conta Corrente Itaú" as const,
    paymentMethod: "PIX" as const,
    status: "confirmado" as const,
    memberName: "André Luiz",
  },
  {
    id: "tx-002",
    type: "receita" as const,
    category: "Ofertas Gerais" as const,
    description: "Ofertas Coletadas no Culto de Celebração (Domingo 19h)",
    amount: 3280.50,
    date: "2026-08-24",
    account: "Conta Corrente Itaú" as const,
    paymentMethod: "Dinheiro" as const,
    status: "confirmado" as const,
  },
  {
    id: "tx-003",
    type: "despesa" as const,
    category: "Energia / Água / Telecom" as const,
    description: "Conta de Energia Elétrica Templo Sede (Neoenergia)",
    amount: 1840.20,
    date: "2026-08-22",
    account: "Conta Corrente Itaú" as const,
    paymentMethod: "Boleto" as const,
    status: "confirmado" as const,
    receiptUrl: "comprovante_neoenergia_0826.pdf",
  },
  {
    id: "tx-004",
    type: "despesa" as const,
    category: "Manutenção & Reformas" as const,
    description: "Manutenção Preventiva do Ar Condicionado Salão Principal",
    amount: 650.00,
    date: "2026-08-20",
    account: "Caixa Físico (Tesouraria)" as const,
    paymentMethod: "PIX" as const,
    status: "confirmado" as const,
  },
  {
    id: "tx-005",
    type: "receita" as const,
    category: "Oferta de Missões" as const,
    description: "Oferta Especial - Projeto Sertão Vivo",
    amount: 2150.00,
    date: "2026-08-18",
    account: "Chave PIX Oficial" as const,
    paymentMethod: "PIX" as const,
    status: "confirmado" as const,
  },
  {
    id: "tx-006",
    type: "despesa" as const,
    category: "Ação Social / Cestas" as const,
    description: "Compra de 30 Cestas Básicas para Assistência Comunitária",
    amount: 2400.00,
    date: "2026-08-15",
    account: "Conta Corrente Itaú" as const,
    paymentMethod: "Boleto" as const,
    status: "confirmado" as const,
  },
  {
    id: "tx-007",
    type: "despesa" as const,
    category: "Preletor / Abono Pastoral" as const,
    description: "Honorários Preletor Convidado - Semanário da Família",
    amount: 800.00,
    date: "2026-08-14",
    account: "Caixa Físico (Tesouraria)" as const,
    paymentMethod: "Dinheiro" as const,
    status: "confirmado" as const,
  },
  {
    id: "tx-008",
    type: "despesa" as const,
    category: "Aluguel & Taxas" as const,
    description: "Aluguel Anexo Kids e Ministério Infantil",
    amount: 3200.00,
    date: "2026-08-10",
    account: "Conta Corrente Itaú" as const,
    paymentMethod: "Transferência" as const,
    status: "confirmado" as const,
  },
  {
    id: "tx-009",
    type: "receita" as const,
    category: "Eventos / Inscrições" as const,
    description: "Lote 1 Inscrições - Acampamento de Jovens 2026",
    amount: 4500.00,
    date: "2026-08-08",
    account: "Chave PIX Oficial" as const,
    paymentMethod: "PIX" as const,
    status: "confirmado" as const,
  },
  {
    id: "tx-010",
    type: "despesa" as const,
    category: "Equipamentos / Som" as const,
    description: "Substituição de Cabos XLR e Microfone Sem Fio Doutrina",
    amount: 1120.00,
    date: "2026-08-28",
    account: "Conta Corrente Itaú" as const,
    paymentMethod: "Boleto" as const,
    status: "pendente" as const,
    notes: "Vencimento em 28/08. Aguardando aprovação do Pr. Presidente.",
  },
]

export const cultoOfferings = [
  {
    id: "co-001",
    date: "2026-08-24",
    serviceName: "Culto de Celebração (Domingo 19h)",
    dizimosAmount: 4850.00,
    ofertasAmount: 3280.50,
    ofertaMissoesAmount: 1200.00,
    totalAmount: 9330.50,
    status: "fechado" as const,
    responsible: "Marcos Oliveira (Tesoureiro)",
  },
  {
    id: "co-002",
    date: "2026-08-20",
    serviceName: "Culto de Doutrina e Oração (Quarta 19h30)",
    dizimosAmount: 1200.00,
    ofertasAmount: 890.00,
    ofertaMissoesAmount: 350.00,
    totalAmount: 2440.00,
    status: "fechado" as const,
    responsible: "Marcos Oliveira (Tesoureiro)",
  },
  {
    id: "co-003",
    date: "2026-08-17",
    serviceName: "Culto da Família (Domingo 19h)",
    dizimosAmount: 6100.00,
    ofertasAmount: 4120.00,
    ofertaMissoesAmount: 1850.00,
    totalAmount: 12070.00,
    status: "fechado" as const,
    responsible: "Lucas Fernandes (Diaconia)",
  },
]

export const rooms: Room[] = [
  {
    id: "room-main",
    name: "Salão Principal",
    capacity: 280,
    description: "Cultos, conferências e reuniões abertas da igreja.",
  },
  {
    id: "room-rehearsal",
    name: "Sala de Ensaio",
    capacity: 18,
    description: "Espaço com instrumentos, retorno e isolamento básico.",
  },
  {
    id: "room-kids",
    name: "Sala Kids",
    capacity: 36,
    description: "Ambiente infantil com tapetes, armários e apoio audiovisual.",
  },
  {
    id: "room-meeting",
    name: "Sala de Reuniões",
    capacity: 16,
    description: "Mesa de planejamento, TV e quadro branco.",
  },
]

export const songs: Song[] = [
  { id: "song-001", title: "Águas de Vida", artist: "Siloé Worship", key: "D", bpm: 72 },
  { id: "song-002", title: "Tua Presença Fica", artist: "Coletivo Casa", key: "G", bpm: 68 },
  {
    id: "song-003",
    title: "Cristo Reina Aqui",
    artist: "Ministério Aliança",
    key: "A",
    bpm: 78,
    referenceUrl: "https://www.youtube.com/results?search_query=Cristo+Reina+Aqui+louvor",
  },
  { id: "song-004", title: "Graça Sobre Graça", artist: "Vozes do Reino", key: "E", bpm: 64 },
  { id: "song-005", title: "Santo é o Senhor", artist: "Comunidade Viva", key: "C", bpm: 70 },
  { id: "song-006", title: "Fonte Inesgotável", artist: "Siloé Worship", key: "F", bpm: 82 },
  { id: "song-007", title: "Meu Refúgio", artist: "Nova Canção", key: "Bb", bpm: 66 },
  {
    id: "song-008",
    title: "Leva-me Mais Perto",
    artist: "Coletivo Graça",
    key: "D",
    bpm: 74,
    referenceUrl: "https://www.youtube.com/results?search_query=Leva-me+Mais+Perto+louvor",
  },
  { id: "song-009", title: "Tudo Entrego", artist: "Voz da Igreja", key: "G", bpm: 60 },
  { id: "song-010", title: "Dia de Celebração", artist: "Ministério Aliança", key: "B", bpm: 104 },
]

export const roomBookings: RoomBooking[] = [
  {
    id: "booking-001",
    roomId: "room-rehearsal",
    requestedBy: "mem-002",
    date: "2026-08-27",
    startTime: "19:30",
    endTime: "21:00",
    purpose: "Ensaio do louvor",
    status: "aprovado",
  },
  {
    id: "booking-002",
    roomId: "room-kids",
    requestedBy: "mem-007",
    date: "2026-08-30",
    startTime: "08:30",
    endTime: "11:30",
    purpose: "Classe especial do ministério infantil",
    status: "aprovado",
  },
  {
    id: "booking-003",
    roomId: "room-meeting",
    requestedBy: "mem-006",
    date: "2026-08-29",
    startTime: "17:00",
    endTime: "18:30",
    purpose: "Planejamento do encontro de jovens",
    status: "pendente",
  },
  {
    id: "booking-004",
    roomId: "room-main",
    requestedBy: "mem-002",
    date: "2026-08-30",
    startTime: "09:00",
    endTime: "11:30",
    purpose: "Culto de domingo",
    status: "aprovado",
  },
  {
    id: "booking-005",
    roomId: "room-rehearsal",
    requestedBy: "mem-002",
    date: "2026-08-26",
    startTime: "19:00",
    endTime: "21:00",
    purpose: "Ensaio da banda",
    status: "aprovado",
  },
  {
    id: "booking-006",
    roomId: "room-kids",
    requestedBy: "mem-007",
    date: "2026-08-26",
    startTime: "15:00",
    endTime: "16:30",
    purpose: "Preparação da decoração",
    status: "pendente",
  },
  {
    id: "booking-007",
    roomId: "room-main",
    requestedBy: "mem-005",
    date: "2026-08-29",
    startTime: "15:00",
    endTime: "18:00",
    purpose: "Ensaios abertos de louvor",
    status: "recusado",
  },
  {
    id: "booking-008",
    roomId: "room-meeting",
    requestedBy: "mem-001",
    date: "2026-08-24",
    startTime: "19:00",
    endTime: "20:30",
    purpose: "Reunião de líderes",
    status: "aprovado",
  },
  {
    id: "booking-009",
    roomId: "room-meeting",
    requestedBy: "mem-005",
    date: "2026-08-28",
    startTime: "14:00",
    endTime: "15:30",
    purpose: "Estudo bíblico das famílias",
    status: "pendente",
  },
]

export const songRequests: SongRequest[] = [
  {
    id: "request-001",
    songTitle: "Fonte Inesgotável",
    artist: "Siloé Worship",
    requestedBy: "mem-004",
    serviceDate: "2026-08-30",
    status: "pendente",
    note: "Combina com a mensagem sobre restauração.",
  },
  {
    id: "request-002",
    songTitle: "Dia de Celebração",
    artist: "Ministério Aliança",
    requestedBy: "mem-006",
    serviceDate: "2026-09-06",
    status: "aprovado",
    note: "Sugestão para abertura do culto.",
  },
  {
    id: "request-003",
    songTitle: "Tudo Entrego",
    requestedBy: "mem-008",
    serviceDate: "2026-08-30",
    status: "recusado",
    note: "Ficou fora do tema desta semana.",
  },
  {
    id: "request-004",
    songTitle: "Leva-me Mais Perto",
    artist: "Coletivo Graça",
    requestedBy: "mem-005",
    serviceDate: "2026-08-30",
    status: "pendente",
    note: "Ideal para o momento de comunhão.",
  },
  {
    id: "request-005",
    songTitle: "Meu Refúgio",
    artist: "Nova Canção",
    requestedBy: "mem-007",
    serviceDate: "2026-08-30",
    status: "pendente",
    note: "Pode ser tocada no encerramento.",
  },
]

export const worshipScale: WorshipScale = {
  id: "scale-001",
  name: "Culto de Domingo",
  date: "2026-08-30",
  time: "09:30",
  entries: [
    { memberId: "mem-002", role: "vocal" },
    { memberId: "mem-005", role: "vocal" },
    { memberId: "mem-004", role: "violão" },
    { memberId: "mem-008", role: "teclado" },
  ],
  songIds: ["song-001", "song-002", "song-005", "song-007"],
}

export const events = [
  { id: "evt-001", title: "Culto de Domingo", date: "30 ago", time: "09:30", room: "Salão Principal" },
  { id: "evt-002", title: "Ensaio de Louvor", date: "27 ago", time: "19:30", room: "Sala de Ensaio" },
  { id: "evt-003", title: "Reunião de Líderes", date: "29 ago", time: "17:00", room: "Sala de Reuniões" },
]

export const notices = [
  {
    id: "notice-001",
    title: "Santa Ceia neste domingo",
    description: "Chegue 20 minutos antes para organização das equipes.",
  },
  {
    id: "notice-002",
    title: "Cadastro de voluntários",
    description: "Novas turmas de recepção e kids serão organizadas nesta semana.",
  },
]

export const socialFamilies = [
  {
    id: "fam-001",
    headName: "Maria das Graças Silva",
    dependentsCount: 4,
    phone: "(61) 98822-1100",
    address: "Quadra 12, Lote 04 - Ceilândia Sul",
    status: "em_acompanhamento" as const,
    assistanceType: "cesta_basica" as const,
    registeredAt: "2026-03-10",
    notes: "Mãe solo, desempregada recentemente. Atendida mensalmente.",
  },
  {
    id: "fam-002",
    headName: "José Carlos Ferreira",
    dependentsCount: 2,
    phone: "(61) 99111-3322",
    address: "Rua 08, Casa 15 - Taguatinga Norte",
    status: "em_acompanhamento" as const,
    assistanceType: "vale_gas" as const,
    registeredAt: "2026-05-18",
    notes: "Apoio com vale-gás e fraldas geriátricas para idoso acamado.",
  },
  {
    id: "fam-003",
    headName: "Francisca Souza Santos",
    dependentsCount: 5,
    phone: "(61) 98455-7766",
    address: "Conjunto B, Casa 02 - Samambaia Norte",
    status: "atendido" as const,
    assistanceType: "cesta_basica" as const,
    registeredAt: "2026-01-20",
    notes: "Família acolhida pelo ministério de ação social.",
  },
  {
    id: "fam-004",
    headName: "Raimundo Nonato",
    dependentsCount: 1,
    phone: "(61) 99333-2211",
    address: "Setor O, QNO 05 - Ceilândia",
    status: "em_acompanhamento" as const,
    assistanceType: "apoio_psicologico" as const,
    registeredAt: "2026-06-12",
    notes: "Encaminhado para atendimento psicológico voluntário da igreja.",
  },
]

export const socialDistributions = [
  {
    id: "dist-001",
    familyId: "fam-001",
    familyName: "Maria das Graças Silva",
    item: "Cesta Básica Completa + Kit Limpeza",
    quantity: 1,
    deliveredAt: "2026-08-20",
    deliveredBy: "Diácono Lucas Fernandes",
  },
  {
    id: "dist-002",
    familyId: "fam-002",
    familyName: "José Carlos Ferreira",
    item: "Vale-Gás 13kg + Fralda Geriátrica G",
    quantity: 1,
    deliveredAt: "2026-08-18",
    deliveredBy: "Mariana Azevedo (Secretaria)",
  },
  {
    id: "dist-003",
    familyId: "fam-003",
    familyName: "Francisca Souza Santos",
    item: "Cesta Básica Tipo A",
    quantity: 2,
    deliveredAt: "2026-08-15",
    deliveredBy: "Equipe de Ação Social",
  },
]

export const pastoralVisits = [
  {
    id: "vis-001",
    memberName: "José Carlos Ferreira",
    visitDate: "2026-08-25",
    pastorName: "Pr. Mateus Silva",
    purpose: "Enfermidade / Hospital" as const,
    status: "realizado" as const,
    notes: "Momento de oração e ceia doméstica no lar. Família fortalecida.",
    privacy: "equipe_pastoral" as const,
  },
  {
    id: "vis-002",
    memberName: "Beatriz Lima & Família",
    visitDate: "2026-08-28",
    pastorName: "Pr. Mateus Silva",
    purpose: "Oração no Lar" as const,
    status: "agendado" as const,
    notes: "Culto no lar agendado a pedido da família.",
    privacy: "equipe_pastoral" as const,
  },
]

export const cellGroups = [
  {
    id: "cell-001",
    name: "Célula Águas Vivas",
    network: "Jovens" as const,
    leaderName: "Tiago Martins",
    coLeaderName: "Camila Rocha",
    hostName: "Casa do Tiago",
    dayOfWeek: "Quinta" as const,
    time: "20:00",
    neighborhood: "Taguatinga Norte",
    address: "QNL 12, Bloco C, Apt 302",
    membersCount: 12,
    targetMembers: 15,
    status: "ativa" as const,
  },
  {
    id: "cell-002",
    name: "Célula Graça & Vida",
    network: "Casais" as const,
    leaderName: "Rafael Monteiro",
    coLeaderName: "Mariana Azevedo",
    hostName: "Residência Monteiro",
    dayOfWeek: "Sexta" as const,
    time: "20:00",
    neighborhood: "Águas Claras",
    address: "Rua das Castanheiras, Lote 14",
    membersCount: 14,
    targetMembers: 16,
    status: "ativa" as const,
  },
  {
    id: "cell-003",
    name: "Célula Manancial",
    network: "Famílias" as const,
    leaderName: "Lucas Fernandes",
    coLeaderName: "Beatriz Lima",
    hostName: "Casa do Lucas",
    dayOfWeek: "Quarta" as const,
    time: "19:30",
    neighborhood: "Ceilândia Sul",
    address: "QNM 18, Conjunto H, Casa 12",
    membersCount: 10,
    targetMembers: 12,
    status: "ativa" as const,
  },
  {
    id: "cell-004",
    name: "Célula Mulheres de Fé",
    network: "Mulheres" as const,
    leaderName: "Priscila Nogueira",
    coLeaderName: "Fernanda Souza",
    hostName: "Residência Priscila",
    dayOfWeek: "Terça" as const,
    time: "15:00",
    neighborhood: "Samambaia Norte",
    address: "QR 312, Conjunto 04, Casa 18",
    membersCount: 11,
    targetMembers: 14,
    status: "ativa" as const,
  },
]

export const cellReports = [
  {
    id: "rep-001",
    cellId: "cell-001",
    cellName: "Célula Águas Vivas",
    meetingDate: "2026-08-21",
    attendeesCount: 11,
    visitorsCount: 3,
    biblesCount: 9,
    conversionsCount: 1,
    offeringAmount: 85.50,
    studyTopic: "Série Identidade em Cristo - Lição 4",
    notes: "Culto abençoado! O visitante Lucas aceitou a Cristo.",
    submittedBy: "Tiago Martins",
  },
  {
    id: "rep-002",
    cellId: "cell-002",
    cellName: "Célula Graça & Vida",
    meetingDate: "2026-08-22",
    attendeesCount: 13,
    visitorsCount: 2,
    biblesCount: 12,
    conversionsCount: 0,
    offeringAmount: 140.00,
    studyTopic: "Comunicação Saudável no Casamento",
    notes: "Momento de comunhão especial com jantar ao final.",
    submittedBy: "Rafael Monteiro",
  },
  {
    id: "rep-003",
    cellId: "cell-003",
    cellName: "Célula Manancial",
    meetingDate: "2026-08-20",
    attendeesCount: 9,
    visitorsCount: 1,
    biblesCount: 8,
    conversionsCount: 0,
    offeringAmount: 60.00,
    studyTopic: "O Poder da Oração em Família",
    submittedBy: "Lucas Fernandes",
  },
]

export const demoUsersByRole: Record<Role, Member> = {
  admin: members[0],
  secretaria: members[9],
  tesoureiro: members[8],
  lider_celula: members[5],
  lider_louvor: members[1],
  lider_salas: members[2],
  membro: members[4],
}

export function getRoleLabel(role: Role) {
  const labels: Record<Role, string> = {
    admin: "Admin",
    secretaria: "Secretaria",
    tesoureiro: "Tesoureiro",
    lider_celula: "Líder de Célula",
    lider_louvor: "Líder de Louvor",
    lider_salas: "Líder de Salas",
    membro: "Membro",
  }

  return labels[role]
}

export function getStatusLabel(status: BookingStatus) {
  const labels: Record<BookingStatus, string> = {
    pendente: "Pendente",
    aprovado: "Aprovado",
    recusado: "Recusado",
  }

  return labels[status]
}

export function getMemberById(memberId: Member["id"]) {
  return members.find((member) => member.id === memberId) ?? members[0]
}

export function getRoomById(roomId: Room["id"]) {
  return rooms.find((room) => room.id === roomId) ?? rooms[0]
}

export function buildApprovalItems(
  bookings: RoomBooking[] = roomBookings,
  requests: SongRequest[] = songRequests
): ApprovalItem[] {
  const roomItems = bookings.map((booking) => {
    const room = getRoomById(booking.roomId)
    const requester = getMemberById(booking.requestedBy)

    return {
      id: booking.id,
      type: "room" as const,
      title: room.name,
      description: booking.purpose,
      requestedBy: requester,
      requestedAt: "Hoje",
      scheduledFor: `${booking.date} · ${booking.startTime}-${booking.endTime}`,
      status: booking.status,
      meta: `${room.capacity} pessoas`,
    }
  })

  const songItems = requests.map((request) => {
    const requester = getMemberById(request.requestedBy)

    return {
      id: request.id,
      type: "song" as const,
      title: request.songTitle,
      description: request.note ?? "Sugestão enviada para avaliação do líder.",
      requestedBy: requester,
      requestedAt: "Esta semana",
      scheduledFor: request.serviceDate,
      status: request.status,
      meta: "Repertório",
    }
  })

  return [...roomItems, ...songItems]
}
